server:
  port: 8087
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/shop
    username: sun
    password: rnrdj123
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        show_sql: true
        format_sql: true


  servlet:
    multipart:
      enabled: true
      location: C:\\upload
      max-file-size: 5MB
      max-request-size: 15MB

upload:
  path: C:\\upload

logging:
  level:
    com.example.demo: debug
mybatis:
  type-aliases-package: com.example.demo
